### ISSUE TITLE
check_tests: edge case: return-type mismatch when no samples are collected

### ISSUE THREAD

**Issue by jayaddison** [P403n1x87/pytest-austin#3]
### Description

While evaluating `austin` (it looks brilliant, thank you!), I encountered an edge case when running `pytest` with `pytest-austin` v0.1.0 on a codebase that does not yet have any tests pytest-marked for sampling, and where tests finish extremely quickly.

### Steps to Reproduce

1. Installed v2.1.1 from Debian/experimental.
2. Installed `pytest-austin` v0.1.0 from PyPi.
3. Ran `pytest` for a short-running test (brief enough that sampling does not occur) without any measurement markers configured.

**Expected behavior:** Tests proceed as usual, but without any performance measurement or side-effects.

**Actual behavior:** An error occurred:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jka/Documents/personal/pytest-austin/.venv/lib/python3.11/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/jka/Documents/personal/pytest-austin/.venv/lib/python3.11/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/jka/Documents/personal/pytest-austin/.venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/jka/Documents/personal/pytest-austin/.venv/lib/python3.11/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/jka/Documents/personal/pytest-austin/.venv/lib/python3.11/site-packages/pluggy/_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/home/jka/Documents/personal/pytest-austin/.venv/lib/python3.11/site-packages/pytest_austin/plugin.py", line 136, in pytest_runtestloop
INTERNALERROR>     session.testsfailed += pytest_austin.check_tests()
INTERNALERROR> TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
For an empty input file this appears highly replicable on my system (~=100%).

### Versions

OS: Debian 12 (bookworm)
Austin: v2.1.1
pytest-austin: v0.1.0

### Additional Information

I think that this line is the cause, and can be updated to `return 0` to resolve the problem:

https://github.com/P403n1x87/pytest-austin/blob/a5e334e180caa618e0bc9f9b51255a1fc9b6273c/pytest_austin/__init__.py#L207

(note: [`mypy`](https://github.com/python/mypy/) also detects this as a possible problem, along with a few other type-checking issues in the codebase)

**Comment by P403n1x87** [comment]
@jayaddison thanks for reporting this. Your proposal makes sense, feel free to open a PR with the fix if you want. Unfortunately I haven't had much time to look after this project so I think it has started to bit-rot.

**Comment by jayaddison** [comment]
Thanks @P403n1x87 - will do.  If possible: could you re-run the GitHub Actions tests on this repository to see what state those are in?  (my guess is that they're going to fail in interesting ways.. hopefully not too difficult to fix)

**Comment by P403n1x87** [comment]
@jayaddison thanks for your PR. I have updated the `devel` branch to re-trigger the jobs. I see some tests succeeding but only because nothing is actually being tested. I think the workflow are currently in an unhelpful state.

**Comment by jayaddison** [comment]
Thanks @P403n1x87 - ok, yep - I see the Python version mismatches compared to what's available in the GitHub runner images nowadays.

I'll try to spend some time soon to restore the gaps (Py3.11 should be easier as it's what I have available locally.. Py3.10 could require some use of containers/older systems to check).
